version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: planeja-postgres
    environment:
      POSTGRES_DB: planeja
      POSTGRES_USER: planeja
      POSTGRES_PASSWORD: planeja123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
