server:
  port: 8080

spring:
  application:
    name: planeja-backend

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:planeja}
    username: ${DB_USER:planeja}
    password: ${DB_PASSWORD:planeja123}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.planeja: DEBUG
    org.springframework.web: DEBUG

pinecone:
  api-key: ${PINECONE_API_KEY}
  index-name: bncc-planeja
  environment: us-east-1
  host: ${PINECONE_HOST}

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-2.5-flash
  base-url: https://generativelanguage.googleapis.com/v1beta

jwt:
  secret: PNcd1MKSv9nv/rNUC4HcMtvx6mGqHYEbQePtIXnYnzw=

  expiration: 3600000
  refresh-token.expiration: 604800000 # 7 days