server:
  port: 8080

spring:
  application:
    name: planeja-backend

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:planeja}
    username: ${DB_USER:planeja}
    password: ${DB_PASSWORD:planeja123}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    com.planeja: DEBUG
    org.springframework.web: DEBUG
